name: deploy-pr

on:
  pull_request: 
    branches: [ 'main' ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-environment:
    runs-on: ubuntu-latest
    env:
      DATE_TIME: $(date +'%Y-%m-%dT%H%M%S')
      RG_NAME: "rg-pull-${{ github.event.pull_request.number }}-$DATE_TIME"
    steps:
    - uses: actions/checkout@v3
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: create resource group
      run: az group create --location norwayeast --name "$RG_NAME"
    - name: deploy platform
      id: deployPlatform
      run: |
        echo "RG_NAME: $RG_NAME"
        deploymentName="platform-${{ github.event.pull_request.number }}-$GITHUB_RUN_NUMBER-$DATE_TIME"
        az deployment group create --mode Complete --resource-group "$RG_NAME" --name "$deploymentName" --template-file ./.platform/main.bicep --parameters main.parameters.pr.json

    - name: echo output
      run: |
        echo "${{ steps.deployPlatform.outputs }}"

    - name: destroy
      if: always()
      run: az group delete --resource-group "$RG_NAME" --yes
