name: deploy-pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'stryker-config.json'
      - 'LICENSE'
      - '.gitignore'
      - '.vscode/*'
      - '.devcontainer/*'

permissions:
  id-token: write
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  basic-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: dotnet workload restore
    - run: dotnet tool restore
    - run: dotnet test
    - run: dotnet stryker
    - uses: actions/upload-artifact@v4
      with:
        name: stryker-mutation-report
        path: StrykerOutput/**/mutation-report.html
        if-no-files-found: error

  deploy-test:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'Test'
    secrets: inherit

  acceptance-tests:
    runs-on: ubuntu-latest
    needs:
    - deploy-test
    - basic-tests
    env:
      SPESIFICATIONS_BASEADDRESS: ${{ needs.deploy-test.outputs.webfrontendUrl }}
    steps:
      - uses: actions/checkout@v4

      - name: Run acceptance tests
        run: |
          echo "SPESIFICATIONS_BASEADDRESS: ${{ env.SPESIFICATIONS_BASEADDRESS }}"

          pushd spesifications
          dotnet build
          pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
          dotnet test
          popd

  deploy-production:
    uses: ./.github/workflows/deploy.yml
    needs: acceptance-tests
    with:
      environment: 'Production'
    secrets: inherit
