name: deploy-pipeline

on:
  # ON PULL REQUEST ONLY FOR TESTING
  pull_request: 
    branches: [ main ]
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'stryker-config.json'
      - 'LICENSE'
      - '.gitignore'
      - '.vscode/*'

permissions:
  id-token: write
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  deploy-test:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'Test'
    secrets: inherit

  acceptance-test:
    runs-on: ubuntu-latest
    needs: deploy-test
    env:
      webfrontendUrl: ${{ needs.deploy-test.outputs.webfrontendUrl }}
    steps:
      - name: Run tests
        run: |
          echo "webfrontendUrl: ${{ env.webfrontendUrl }}"

          pushd spesifications/spesification

          export SPESIFICATIONS_BASEADDRESS=${{ env.webfrontendUrl }}
          dotnet test

          popd

  deploy-production:
    uses: ./.github/workflows/deploy.yml
    needs: acceptance-test
    with:
      environment: 'Production'
    secrets: inherit
