name: deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      containerRegistryUrl:
        required: true
        type: string
      managedIdentityId:
        required: true
        type: string
      managedIdentityClientId:
        required: true
        type: string
    outputs:
      webfrontendUrl:
        value: ${{ jobs.deploy.outputs.webfrontendUrl }}

env:
  GITHUB_SHA_SHORT: $(git rev-parse --short ${{ github.sha }})
  DEPLOY_TIMESTAMP: $(date +%Y-%m-%dT%H.%M.%S)
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    outputs:
      webfrontendUrl: ${{ steps.deploy-app-environment.outputs.webfrontendLatestRevisionFqdn }}

    env:
      RG_ACR: ${{ vars.RG_ACR }}
      RG_APP: ${{ vars.RG_APP }}
      APISERVICE_CONTAINERREPOSITORY: ${{ vars.APISERVICE_CONTAINERREPOSITORY }}
      WEBFRONTEND_CONTAINERREPOSITORY: ${{ vars.WEBFRONTEND_CONTAINERREPOSITORY }}
      CONTAINER_VERSION_TAG: ${{ github.run_id }}-${{ github.run_attempt }}
      ASPNETCORE_ENVIRONMENT: ${{ inputs.environment }}

    steps:
    - uses: actions/checkout@v4

    - name: 'Az login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}



    - name: login containerRegistry
      run: az acr login --name ${{ inputs.containerRegistryUrl }}

    - name: publish apiservice
      run: |
        echo "Publishing apiservice"

        pushd src/Test1.ApiService

        dotnet publish \
          -p ContainerRegistry='${{ inputs.containerRegistryUrl }}' \
          -p PublishProfile=DefaultContainer \
          -p ContainerImageTags='"${{ env.CONTAINER_VERSION_TAG }}"' \
          -p ContainerRepository=${{ env.APISERVICE_CONTAINERREPOSITORY }}

        popd

    - name: publish webfrontend
      run: |
        echo "Publishing webfrontend"

        pushd src/Test1.Web

        dotnet publish \
          -p ContainerRegistry='${{ inputs.containerRegistryUrl }}' \
          -p PublishProfile=DefaultContainer \
          -p ContainerImageTags='"${{ env.CONTAINER_VERSION_TAG }}"' \
          -p ContainerRepository=${{ env.WEBFRONTEND_CONTAINERREPOSITORY }}

        popd

    - name: deploy app environment
      id: deploy-app-environment
      env:
        deploymentName: ${{ env.RG_APP }}-${{ env.DEPLOY_TIMESTAMP }}-${{ env.GITHUB_SHA_SHORT }}
        APISERVICE_CONTAINER_IMAGE: ${{ inputs.containerRegistryUrl }}/${{ env.APISERVICE_CONTAINERREPOSITORY }}:${{ env.CONTAINER_VERSION_TAG }}
        WEBFRONTEND_CONTAINER_IMAGE: ${{ inputs.containerRegistryUrl }}/${{ env.WEBFRONTEND_CONTAINERREPOSITORY }}:${{ env.CONTAINER_VERSION_TAG }}
      run: |
        echo "Deploying applications"

        az group create --location norwayeast --name ${{ env.RG_APP }}

        az bicep lint --file .platform/main.app.bicep

        deployResult=$(az deployment group create \
          --mode Incremental \
          --resource-group "${{ env.RG_APP }}" \
          --name "${{ env.deploymentName }}" \
          --template-file ./.platform/main.app.bicep \
          --parameters aspnetcoreEnvironment=${{ env.ASPNETCORE_ENVIRONMENT }} \
          --parameters containerRegistryUrl=${{ inputs.containerRegistryUrl }} \
          --parameters managedIdentityClientId=${{ inputs.managedIdentityClientId }} \
          --parameters managedIdentityId=${{ inputs.managedIdentityId }} \
          --parameters apiserviceContainerImage=${{ env.APISERVICE_CONTAINER_IMAGE }} \
          --parameters webfrontendContainerImage=${{ env.WEBFRONTEND_CONTAINER_IMAGE }} \
          --parameters deployTimestamp=${{ env.DEPLOY_TIMESTAMP }} \
          )
        
        echo "# Deploy result"
        echo $deployResult
        echo "# ---"

        echo "# setting outputs"
        
        # webfrontendLatestRevisionFqdn
        webfrontendLatestRevisionFqdn=$(echo $deployResult | jq --raw-output '.properties.outputs.webfrontendLatestRevisionFqdn.value')
        echo "webfrontendLatestRevisionFqdn=$webfrontendLatestRevisionFqdn" >> $GITHUB_OUTPUT
        echo "webfrontendLatestRevisionFqdn: $webfrontendLatestRevisionFqdn"
