name: deploy-pr

on:
  pull_request: 
    branches: [ 'main' ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-environment:
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_PLATFORM_NAME: "platform-${{ github.run_number }}-${{ github.run_attempt }}"
      RG_NAME: "rg-pull-${{ github.event.pull_request.number }}-${{ github.run_number }}-${{ github.run_attempt }}"
    steps:
    - uses: actions/checkout@v3

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: create resource group
      run: az group create --location norwayeast --name ${{ env.RG_NAME }}

    - name: deploy platform
      id: deployPlatform
      run: |
        echo "RG_NAME: ${{ env.RG_NAME }}"
        az deployment group create --mode Complete --resource-group "${{ env.RG_NAME }}" --name "${{ env.DEPLOYMENT_PLATFORM_NAME }}" --template-file ./.platform/main.bicep --parameters @./.platform/main.parameters.pr.json > az_create_output.txt
        echo "### OUTPUT ###"
        cat az_create_output.txt
        echo "### OUTPUTS ###"
        cat az_create_output.txt | jq --raw-output '.properties.outputs.containerAppsEnvironmentId.value'
        echo "### OUTPUTS SET ###"
        # containerAppsEnvironmentId
        containerAppsEnvironmentId=$(cat az_create_output.txt | jq --raw-output '.properties.outputs.containerAppsEnvironmentId.value')
        echo "containerAppsEnvironmentId=$containerAppsEnvironmentId" >> $GITHUB_OUTPUT
        # containerRegistryId
        containerRegistryId=$(cat az_create_output.txt | jq --raw-output '.properties.outputs.containerRegistryId.value')
        echo "containerRegistryId=$containerRegistryId" >> $GITHUB_OUTPUT
        # managedIdentityId
        managedIdentityId=$(cat az_create_output.txt | jq --raw-output '.properties.outputs.managedIdentityId.value')
        echo "managedIdentityId=$managedIdentityId" >> $GITHUB_OUTPUT

    - name: echo output
      run: |
        echo "containerAppsEnvironmentId: ${{ steps.deployPlatform.outputs.containerAppsEnvironmentId }}"
        echo "containerRegistryId: ${{ steps.deployPlatform.outputs.containerRegistryId }}"
        echo "managedIdentityId: ${{ steps.deployPlatform.outputs.managedIdentityId }}"

    - name: destroy
      if: always()
      run: az group delete --resource-group ${{ env.RG_NAME }} --yes
