name: deploy-pr

on:
  pull_request: 
    branches: [ 'main' ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-environment:
    runs-on: ubuntu-latest
    env:
      RG_NAME: "rg-pull-${{ github.event.pull_request.number }}"
    steps:
    - uses: actions/checkout@v3
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: deploy
      run: |
        az group create --location norwayeast --name "$RG_NAME"
        az deployment group create --mode Complete --resource-group "$RG_NAME" --template-file ./.platform/main.bicep
    
    - name: destroy
      if: always()
      run: az group delete --resource-group "$RG_NAME" --yes
