name: deploy-pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'stryker-config.json'
      - 'LICENSE'
      - '.gitignore'
      - '.vscode/*'
      - '.devcontainer/*'

permissions:
  id-token: write
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  deploy-test:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'Test'
    secrets: inherit

  acceptance-test:
    runs-on: ubuntu-latest
    needs: deploy-test
    env:
      SPESIFICATIONS_BASEADDRESS: ${{ needs.deploy-test.outputs.webfrontendUrl }}
    steps:
      - uses: actions/checkout@v4

      - name: Run basic tests
        run: |
          echo "running basic tests"

          # TODO remove intentinal mistake
          dotnet tset

      - name: Run acceptance tests
        run: |
          echo "SPESIFICATIONS_BASEADDRESS: ${{ env.SPESIFICATIONS_BASEADDRESS }}"

          pushd spesifications/spesification

          dotnet test

          popd

  deploy-production:
    uses: ./.github/workflows/deploy.yml
    needs: acceptance-test
    with:
      environment: 'Production'
    secrets: inherit
