name: deploy-pr

on:
  pull_request: 
    branches: [ 'main' ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RG_ACR: ${{ vars.RG_ACR_PREFIX }}-${{ github.event.pull_request.number }}-${{ github.run_number }}-${{ github.run_attempt }}
      RG_APP: ${{ vars.RG_APP_PREFIX }}-${{ github.event.pull_request.number }}-${{ github.run_number }}-${{ github.run_attempt }}
      CONTAINER_VERSION_TAG: "pull-${{ github.event.pull_request.number }}-${{ github.run_number }}-${{ github.run_attempt }}"
    
    # environment: ###TODO
    
    steps:
    - uses: actions/checkout@v3

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}    
    
    - name: deploy acr
      id: deployAcr
      run: |
        echo "Deploying Container registry"

        az group create --location norwayeast --name ${{ env.RG_ACR }}

        # TODO deploy bicep

    - name: publish apps
      run: |
        echo "Publishing apps"

        # TODO publish apps and push to ACR

    - name: deploy apps
      run: |
        echo "Deploying applications"

        az group create --location norwayeast --name ${{ env.RG_APP }}

        # TODO deploy bicep

    - name: destroy
      if: always()
      run: |
        echo "Cleaning up"
        az group delete --resource-group ${{ env.RG_ACR }} --yes
        az group delete --resource-group ${{ env.RG_APP }} --yes
