name: deploy-pr

on:
  pull_request: 
    branches: [ 'main' ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-environment:
    runs-on: ubuntu-latest
    env:
      RG_NAME: "rg-pull-${{ github.event.pull_request.number }}"
    steps:
    - uses: actions/checkout@v3
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: deploy platform
      run: |
        datetime=$(date +'%Y-%m-%dT%H%M%S')
        deploymentName="platform-${{ github.event.pull_request.number }}-$GITHUB_RUN_NUMBER-$datetime"
        az deployment sub create --template-file ./.platform/main.bicep --name "$deploymentName" --location norwayeast --parameters resourceGroupName=$RG_NAME

    - name: destroy
      if: always()
      run: az group delete --resource-group "$RG_NAME" --yes
