name: deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  GITHUB_SHA_SHORT: $(git rev-parse --short ${{ github.sha }})
  DEPLOY_TIMESTAMP: $(date +%Y-%m-%dT%H.%M.%S)
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    env:
      RG_ACR: ${{ vars.RG_ACR }}
      RG_APP: ${{ vars.RG_APP }}
      APISERVICE_CONTAINERREPOSITORY: ${{ vars.APISERVICE_CONTAINERREPOSITORY }}
      WEBFRONTEND_CONTAINERREPOSITORY: ${{ vars.WEBFRONTEND_CONTAINERREPOSITORY }}
      CONTAINER_VERSION_TAG: ${{ github.run_id }}-${{ github.run_attempt }}
      ASPNETCORE_ENVIRONMENT: ${{ inputs.environment }}

    steps:
    - uses: actions/checkout@v3

    - name: 'Az login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: deploy acr
      id: deployAcr
      env:
        deploymentName: ${{ env.RG_ACR }}-${{ env.DEPLOY_TIMESTAMP }}-${{ env.GITHUB_SHA_SHORT }}
      run: |
        echo "Deploying Container registry"
        echo "deploymentName: ${{ env.deploymentName }}"

        az group create --location norwayeast --name ${{ env.RG_ACR }}

        deployResult=$(az deployment group create \
          --mode Complete \
          --resource-group "${{ env.RG_ACR }}" \
          --name "${{ env.deploymentName }}" \
          --template-file ./.platform/main.acr.bicep \
          )

        echo "# Deploy result"
        echo $deployResult
        echo "# ---"
        
        echo "# setting outputs"
        
        # containerRegistryUrl
        containerRegistryUrl=$(echo $deployResult | jq --raw-output '.properties.outputs.containerRegistryUrl.value')
        echo "containerRegistryUrl=$containerRegistryUrl" >> $GITHUB_OUTPUT
        # managedIdentityId
        managedIdentityId=$(echo $deployResult | jq --raw-output '.properties.outputs.managedIdentityId.value')
        echo "managedIdentityId=$managedIdentityId" >> $GITHUB_OUTPUT
        # managedIdentityClientId
        managedIdentityClientId=$(echo $deployResult | jq --raw-output '.properties.outputs.managedIdentityClientId.value')
        echo "managedIdentityClientId=$managedIdentityClientId" >> $GITHUB_OUTPUT
        
        echo "# done"

    - name: login containerRegistry
      run: az acr login --name ${{ steps.deployAcr.outputs.containerRegistryUrl }}

    - name: publish apiservice
      run: |
        echo "Publishing apiservice"

        pushd src/Test1.ApiService

        dotnet publish \
          -p ContainerRegistry='${{ steps.deployAcr.outputs.containerRegistryUrl }}' \
          -p PublishProfile=DefaultContainer \
          -p ContainerImageTags='"${{ env.CONTAINER_VERSION_TAG }}"' \
          -p ContainerRepository=${{ env.APISERVICE_CONTAINERREPOSITORY }}

        popd

    - name: publish webfrontend
      run: |
        echo "Publishing webfrontend"

        pushd src/Test1.Web

        dotnet publish \
          -p ContainerRegistry='${{ steps.deployAcr.outputs.containerRegistryUrl }}' \
          -p PublishProfile=DefaultContainer \
          -p ContainerImageTags='"${{ env.CONTAINER_VERSION_TAG }}"' \
          -p ContainerRepository=${{ env.WEBFRONTEND_CONTAINERREPOSITORY }}

        popd
