name: pr

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@4
    - name: run basic tests
      run: |
        dotnet workload restore
        dotnet test --no-build --verbosity normal
  bicep-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@4
    - name: bicep lint
      run: |
        az bicep lint --file .platform/main.acr.bicep
        az bicep lint --file .platform/main.app.bicep
